---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: General
- type: directory
  path: "**/*"
  label: Content
  create: all
  match: "*.md"
  exclude: "**/*.*"
- type: directory
  path: "."
  label: Directory
  create: all
  match: "**/*"
- type: document
  path: "."
  label: New post
upload_dir: ".vuepress/public"
public_path: ".vuepress/public"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: vuepress build -d .vuepress/dist
  publish_command: vuepress build -d .vuepress/dist
  preview_output_directory: ".vuepress/dist"
  output_directory: ".vuepress/dist"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
